export const fakeUsers = [
  {
    id: "USR001",
    name: "Nguyễn Văn A",
    email: "nguyenvana@gmail.com",
    phone: "0912345001",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1",
    role: "Quản trị viên",
    roleVariant: "destructive",
    status: "active",
  },
  {
    id: "USR002",
    name: "Trần Thị B",
    email: "tranthib@gmail.com",
    phone: "0912345002",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=2",
    role: "Cư dân",
    roleVariant: "info",
    status: "active",
  },
  {
    id: "USR003",
    name: "Lê Văn C",
    email: "levanc@gmail.com",
    phone: "0912345003",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=3",
    role: "Doanh nghiệp",
    roleVariant: "purple",
    status: "active",
  },
  {
    id: "USR004",
    name: "Phạm Thị D",
    email: "phamthid@gmail.com",
    phone: "0912345004",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=4",
    role: "Người thu gom",
    roleVariant: "success",
    status: "active",
  },
  {
    id: "USR005",
    name: "Hoàng Văn E",
    email: "hoangvane@gmail.com",
    phone: "0912345005",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=5",
    role: "Cư dân",
    roleVariant: "info",
    status: "blocked",
  },
  {
    id: "USR006",
    name: "Vũ Thị F",
    email: "vuthif@gmail.com",
    phone: "0912345006",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=6",
    role: "Cư dân",
    roleVariant: "info",
    status: "active",
  },
  {
    id: "USR007",
    name: "Đỗ Văn G",
    email: "dovang@gmail.com",
    phone: "0912345007",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=7",
    role: "Doanh nghiệp",
    roleVariant: "purple",
    status: "active",
  },
  {
    id: "USR008",
    name: "Bùi Thị H",
    email: "buithih@gmail.com",
    phone: "0912345008",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=8",
    role: "Cư dân",
    roleVariant: "info",
    status: "blocked",
  },
];
