const ROLES = {
  ADMIN: 1,
  ENTERPRISE: 2,
  COLLECTOR: 3,
  CITIZEN: 4
}

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED'
}

const NOTIFICATION_TYPES = {
  // Citizen triggers
  COLLECTION_SCHEDULED: 'COLLECTION_SCHEDULED',
  POINT_REWARDED: 'POINT_REWARDED',
  COLLECTION_COMPLETED: 'COLLECTION_COMPLETED',
  REPORT_ACCEPTED: 'REPORT_ACCEPTED',
  REPORT_REJECTED: 'REPORT_REJECTED',
  REPORT_ASSIGNED: 'REPORT_ASSIGNED',

  // Enterprise triggers
  NEW_REPORT_PENDING: 'NEW_REPORT_PENDING',
  REPORT_COMPLETED: 'REPORT_COMPLETED',

  // Collector triggers
  NEW_ASSIGNMENT: 'NEW_ASSIGNMENT'
}

module.exports = { ROLES, USER_STATUS, NOTIFICATION_TYPES }
