const ROLES = {
  ADMIN: 1,
  ENTERPRISE: 2,
  COLLECTOR: 3,
  CITIZEN: 4
}

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED'
}

const NOTIFICATION_TYPES = {
  // Citizen triggers
  COLLECTION_SCHEDULED: 'COLLECTION_SCHEDULED',
  POINT_REWARDED: 'POINT_REWARDED',
  COLLECTION_COMPLETED: 'COLLECTION_COMPLETED',
  VIOLATION_WARNING: 'VIOLATION_WARNING',
  POINT_DEDUCTED: 'POINT_DEDUCTED',
  REPORT_BLOCKED: 'REPORT_BLOCKED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  REPORT_ACCEPTED: 'REPORT_ACCEPTED',
  REPORT_REJECTED: 'REPORT_REJECTED',
  REPORT_ASSIGNED: 'REPORT_ASSIGNED',

  // Enterprise triggers
  NEW_REPORT_PENDING: 'NEW_REPORT_PENDING',
  REPORT_COMPLETED: 'REPORT_COMPLETED',
  REPORT_REJECTED_BY_COLLECTOR: 'REPORT_REJECTED_BY_COLLECTOR',

  // Collector triggers
  NEW_ASSIGNMENT: 'NEW_ASSIGNMENT',

  // Admin triggers
  NEW_COMPLAINT_RECEIVED: 'NEW_COMPLAINT_RECEIVED',
  NEW_REPORT_RECEIVED: 'NEW_REPORT_RECEIVED'
}

module.exports = { ROLES, USER_STATUS, NOTIFICATION_TYPES }
